### ISSUE TITLE
Unused ideas!

### ISSUE THREAD

**Issue by adituv** [Trans-Code/Trans-Code.github.io#3]
Several of the initial proposed ideas went unused; it could be useful to keep them as prompts for a future hack day.  Here's the information on mine I tweeted to [trans*code](https://twitter.com/IridianSkies/status/723804461664243712)

A database on songs, containing information on their lyrical content, such as trigger warnings and whether they contain explicit lyrics.  The main interface would just be a database browser, but a possible extension is as a music player and organiser where you can filter on certain warning tags, for example.

**Comment by nceder** [comment]
Very good point. Sadly I forgot to take a picture of the board before I erased it, but perhaps people will remember and prompt me. I'll try to include it in the post-event email.

**Comment by geokala** [comment]
It probably wouldn't be overly painful to add this as an extra page, so people who were stuck for ideas could look at that on/before similar events.

That also means that there's a clear split between "We have something like this, maybe" and "We'd like something like this, maybe"

**Comment by adituv** [comment]
> so people who were stuck for ideas could look at that on/before similar events.

Absolutely; this was my thinking when I proposed this.  It wasn't so necessary this time because there were so many great ideas, but I remember that ideas came a little slower at the first event.

**Comment by lpil** [comment]
I'll implement this feature.

**Comment by nceder** [comment]
That would be brilliant! Thanks!

**Comment by lpil** [comment]
Opened a PR :)

**Comment by nceder** [comment]
Many thanks, Louis!

I'll try to fill in some from earlier hackdays and I'll publish this for contributions.
