### ISSUE TITLE
Visual design needed

### ISSUE THREAD

**Issue by lpil** [Trans-Code/Trans-Code.github.io#6]
Hello!

It's be great if someone with graphic design and UX skills (or just an interest!) could make some mock ups for what the website could to look like.

I'm happy to contribute to the implementation of the designs one they are ready. :)

Cheers,
Louis

**Comment by lpil** [comment]
Pinging @scripttease, interested in helping out? :)

**Comment by scripttease** [comment]
Oooooh yes, I'd love to. Gimme a few days. :octocat: :hamster: :heart_decoration:

**Comment by nceder** [comment]
That would be lovely, thanks!
